### ISSUE TITLE
Hangs when opening gif file.

### ISSUE THREAD

**Issue by SirObby** [Lohkdesgds/ImageViewer#1]
Well it just doesn't close like the close button doesn't close the app.

**Comment by Lohkdesgds** [comment]
It still won't load GIFs, but now it allows you to kill after some time if it detects it took too long to load. I think this is nicer than just checking extension because what if the file is .jpg, but it isn't, or maybe it's corrupted, I don't know. ([v2.0.2](https://github.com/Lohkdesgds/ImageViewer/releases/tag/v2.0.2))
